### PR TITLE
fix: http

### LINKED ISSUE #3: v1 tracking
- [x] gRPC #1 
  - [x] examples
- [x] HTTP #2 
  - [x] live
  - [x] ready
  - [x] terminate
  - [x] examples
  - [x] unit tests
- [x] Documentation
  - [x] basic readme
  - [x] enhance readme docs with k8s config examples

### PR DESCRIPTION
**Pull request by bh90210**

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -0,0 +1,4 @@
+test/
+*.pb.gz
+*.test
+test.sh
```
Comment (bh90210) [inline .gitignore]: return line

File: healthz.go [hunk 2]
```diff
@@ -1,70 +1,67 @@
...
 )
 
-type State int
+var s state
 
-const (
-	READY State = iota
-	LIVE
-)
+// Start .
```
Comment (bh90210) [inline healthz.go]: document better

File: healthz_test.go [hunk 3]
```diff
@@ -0,0 +1,102 @@
+package healthz
```
Comment (bh90210) [inline healthz_test.go:1]: finish tests

**Review by bh90210 — COMMENTED** [review]
- [x] line
- [x] documentation
- [x] unit tests

**Comment by bh90210** [comment]
- [x] variable GET handler endpoint
- [x] variable port

**Comment by bh90210** [comment]
- [x] remove namespace from examples

**Comment by bh90210** [comment]
- [x] CI to build/push http example on docker hub

**Comment by bh90210** [comment]
- [ ] add documentation on README for relevant k8s configs settings

**Review by bh90210 — COMMENTED** [review]
:+1:

**Review by bh90210 — COMMENTED** [review]
:+1:
